# Generated by Django 3.2.7 on 2021-10-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_categories_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_winner',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.bid'),
        ),
    ]
