# Generated by Django 3.2.7 on 2021-10-04 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='current_bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
