# Generated by Django 3.2.7 on 2021-10-06 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20211006_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='bids_numbers',
            new_name='bids_number',
        ),
    ]
