# Generated by Django 3.2.7 on 2021-10-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20211007_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='bids_number',
        ),
    ]
